Keep form entries when there is an error
WildCodeSchool/tours-php-2009-project2-mybooks pull request #17
Opened 2020-11-11 13:15 UTC by AurelieFqt

2020-11-11 14:16 UTC, axelhamil approved these changes

2020-11-11 15:48 UTC, YannRaulet approved these changes

2020-11-11 16:44 UTC, MorganeGrenes approved these changes

2020-11-12 08:18 UTC, RomainClair requested changes
composer.phar must not be in the repository
The composer.lock should not changer since it seems this PR doesn't change the repository dependencies.

2020-11-12 08:18 UTC, RomainClair commented on src/Controller/BookController.php
> +                $bookArray['hasBeenRead'] = $read;
If you want all the books and the uncompleted book from the form, you probably should have different variables.

And you should only keep the valid fields and not take everything from $_POST blindly

2020-11-12 08:34 UTC, closed without merging