Search bar functionality
WildCodeSchool/tours-php-2009-project2-mybooks pull request #18
Opened 2020-11-11 16:01 UTC by YannRaulet

2020-11-11 16:42 UTC, MorganeGrenes approved these changes, later dismissed

2020-11-12 08:15 UTC, AurelieFqt submitted a review, later dismissed

2020-11-12 12:24 UTC, rickifox approved these changes

2020-11-12 12:32 UTC, rickifox requested changes
conflicts

2020-11-12 12:56 UTC, RomainClair requested changes

2020-11-12 12:56 UTC, RomainClair commented on src/Controller/BookController.php
> +            ) {
You should verify if $_GET["dataField"] exists before checking it's value.

2020-11-12 12:56 UTC, RomainClair commented on src/routing.php
> +$routeParts = explode('/', ltrim(strtok($_SERVER['REQUEST_URI'], '?'), '/') ?: HOME_PAGE);
You shouldn't change the framework

2020-11-18 09:15 UTC, AurelieFqt approved these changes, later dismissed

2020-11-18 09:48 UTC, AurelieFqt submitted a review, later dismissed

2020-11-18 10:30 UTC, MorganeGrenes approved these changes, later dismissed

2020-11-18 10:47 UTC, AurelieFqt approved these changes

2020-11-18 10:48 UTC, MorganeGrenes approved these changes

2020-11-18 10:59 UTC, RomainClair approved these changes

2020-11-18 11:10 UTC, rickifox approved these changes

2020-11-18 11:14 UTC, merged