View first version mobile-first
WildCodeSchool/tours-php-2009-project2-mybooks pull request #2
Opened 2020-10-29 09:10 UTC by YannRaulet

2020-10-29 09:31 UTC, MorganeGrenes approved these changes, later dismissed

2020-10-29 09:52 UTC, rickifox approved these changes, later dismissed
It's OK to me

2020-10-29 09:52 UTC, axelhamil approved these changes, later dismissed
All it's ok.

2020-10-29 11:30 UTC, RomainClair requested changes
Don't add everything in each PR.

PR must be atomic : one US/Feature

2020-10-29 11:30 UTC, RomainClair commented on config/config.php
> +define('HOME_PAGE', 'Livre/index');
It should be livre (with a lowercase "l")

2020-11-02 10:26 UTC, MorganeGrenes approved these changes

2020-11-02 10:29 UTC, MorganeGrenes approved these changes

2020-11-02 11:09 UTC, rickifox approved these changes

2020-11-02 15:27 UTC, closed without merging