Form
WildCodeSchool/tours-php-2009-project2-mybooks pull request #6
Opened 2020-11-02 17:17 UTC by axelhamil

Added form and prepared future functionalities

2020-11-02 17:28 UTC, rickifox approved these changes

2020-11-02 18:08 UTC, AurelieFqt approved these changes

2020-11-02 19:04 UTC, YannRaulet approved these changes

2020-11-02 21:23 UTC, MorganeGrenes approved these changes

2020-11-04 08:36 UTC, RomainClair requested changes
You should use english for your identifiers

2020-11-04 14:41 UTC, closed without merging